## 205229118
## Mahalakshmi S

In [59]:
import numpy as np

In [60]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

<h3 style='color:blue'>Implement Mean Absolute Error</h3>

In [61]:
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)
    print("Total error is:",total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is:",mae)
    return mae

In [62]:
mae(y_predicted, y_true)

Total error is: 2.5
Mean absolute error is: 0.5


0.5

**Implement same thing using numpy in much easier way**

In [63]:
np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [64]:
np.mean(np.abs(y_predicted-y_true))

0.5

In [65]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))

In [66]:
mae_np(y_predicted, y_true)

0.5

<h3 style='color:blue'>Implement Log Loss or Binary Cross Entropy</h3>

In [67]:
np.log([0])

<ipython-input-67-faee82fd9f21>:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [68]:
epsilon = 1e-15

In [69]:
np.log([1e-15])

array([-34.53877639])

In [70]:
y_predicted

array([1, 1, 0, 0, 1])

In [71]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [72]:
1-epsilon

0.999999999999999

In [73]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [74]:
y_predicted_new = np.array(y_predicted_new)

In [75]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [76]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

In [77]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [78]:
log_loss(y_true, y_predicted)

17.2696280766844

# Changed coding

In [79]:
y_predicted3 = np.array([1,1,0,0,1,1,0,1,1,0])   ### Here I changed Variable name as y_predicted3 and i changed values also...
y_true3 = np.array([0.30,0.7,1,0,0.5,0.60,1,0.3,0.40,0])

In [80]:
def mae(y_predicted3, y_true3):
    total_error = 0
    for yp, yt in zip(y_predicted3, y_true3):
        total_error += abs(yp - yt)
    print("Total error is:",total_error)
    mae = total_error/len(y_predicted3)
    print("Mean absolute error is:",mae)
    return mae

In [81]:
mae(y_predicted3, y_true3)

Total error is: 5.199999999999999
Mean absolute error is: 0.5199999999999999


0.5199999999999999

In [82]:
np.abs(y_predicted3-y_true3)

array([0.7, 0.3, 1. , 0. , 0.5, 0.4, 1. , 0.7, 0.6, 0. ])

In [83]:
np.mean(np.abs(y_predicted3-y_true3))

0.5199999999999999

In [84]:
def mae_np(y_predicted3, y_true3):
    return np.mean(np.abs(y_predicted3-y_true3))

In [85]:
mae_np(y_predicted3, y_true3)

0.5199999999999999

In [86]:
np.log([0])

<ipython-input-86-faee82fd9f21>:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [87]:
epsilon1 = 1e-15

In [88]:
np.log([1e-15])

array([-34.53877639])

In [89]:
y_predicted3

array([1, 1, 0, 0, 1, 1, 0, 1, 1, 0])

In [90]:
y_predicted3_new1 = [max(i,epsilon1) for i in y_predicted3]
y_predicted3_new1

[1, 1, 1e-15, 1e-15, 1, 1, 1e-15, 1, 1, 1e-15]

In [91]:
1-epsilon1

0.999999999999999

In [92]:
y_predicted3_new1 = [min(i,1-epsilon) for i in y_predicted_new1]
y_predicted3_new1

[0.999999999999999,
 0.999999999999999,
 1e-15,
 1e-15,
 0.999999999999999,
 0.999999999999999,
 1e-15,
 0.999999999999999,
 0.999999999999999,
 1e-15]

In [93]:
y_predicted_new1 = np.array(y_predicted_new1)

In [94]:
np.log(y_predicted_new1)

array([  0.        ,   0.        , -34.53877639, -34.53877639,
         0.        ,   0.        , -34.53877639,   0.        ,
         0.        , -34.53877639])

In [95]:
-np.mean(y_true3*np.log(y_predicted_new1)+(1-y_true3)*np.log(1-y_predicted_new1))

<ipython-input-95-a0e952c29c89>:1: RuntimeWarning: divide by zero encountered in log
  -np.mean(y_true3*np.log(y_predicted_new1)+(1-y_true3)*np.log(1-y_predicted_new1))


inf

In [96]:
def log_loss(y_true3, y_predicted3):
    y_predicted_new1 = [max(i,epsilon) for i in y_predicted3]
    y_predicted_new1 = [min(i,1-epsilon) for i in y_predicted_new1]
    y_predicted_new1 = np.array(y_predicted_new1)
    return -np.mean(y_true3*np.log(y_predicted_new1)+(1-y_true3)*np.log(1-y_predicted_new1))

In [97]:
log_loss(y_true3, y_predicted3)

17.960419596531217

<h3 style='color:purple'>Exercise</h3>

Implement mean squared error (or MSE) in two ways,

1) Without using numpy (i.e. using plain python)

2) With the use of numpy

[Solution](https://github.com/codebasics/deep-learning-keras-tf-tutorial/blob/main/5_loss/loss_function_exercise_solution.ipynb)

### 1) Without using numpy (i.e. using plain python)

In [98]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [99]:
def mse(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip(y_true, y_predicted):
        total_error += (yt-yp)**2
    print("Total Squared Error:",total_error)
    mse = total_error/len(y_true)
    print("Mean Squared Error:",mse)
    return mse

In [100]:
mse(y_true, y_predicted)

Total Squared Error: 1.83
Mean Squared Error: 0.366


0.366

### 2) With the use of numpy

In [101]:
np.mean(np.square(y_true-y_predicted))

0.366

# Changed coding

### 1) Without using numpy (i.e. using plain python)

In [102]:
y_predicted4 = np.array([1,1,0,0,1,0,1,1,0])   #Here I changed values for the variable y_predicted4 and y_true4.....
y_true4 = np.array([0.30,0.7,1,0,0.5,1,0.7,0.6,0.4])

In [103]:
def mse(y_true4, y_predicted4):
    total_error = 0
    for yt, yp in zip(y_true4, y_predicted4):
        total_error += (yt-yp)**2
    print("Total Squared Error:",total_error)
    mse = total_error/len(y_true4)
    print("Mean Squared Error:",mse)
    return mse

In [104]:
mse(y_true4, y_predicted4)

Total Squared Error: 3.24
Mean Squared Error: 0.36000000000000004


0.36000000000000004

### 2) With the use of numpy

In [105]:
np.mean(np.square(y_true4-y_predicted4))

0.36000000000000004