## PDL Lab3: Introduction to Tensors - Part I

In [1]:
import tensorflow as tf
import numpy as np

### Basics

In [2]:
a = [1,2,3,4]

In [3]:
 a[2]

3

In [4]:
#As another example, suppose we have this 2d-array:
dd = [
[1,2,3],
[4,5,6],
[7,8,9]
]

In [5]:
 dd[0][2]

3

### Tensor Axes Example

In [17]:
dd = [
[1,2,3],
[4,5,6],
[7,8,9]
]
                 

In [18]:
 dd[0]

[1, 2, 3]

In [19]:
 dd[1]

[4, 5, 6]

In [20]:
 dd[2]

[7, 8, 9]

In [21]:
 dd[0][0]

1

In [22]:
dd[1][0]

4

In [23]:
dd[2][0]

7

In [24]:
dd[0][1]

2

In [25]:
dd[1][1]

5

In [26]:
dd[2][1]

8

In [27]:
dd[0][2]

3

In [28]:
dd[1][2]

6

In [31]:
dd[2][2]

9

### Shape of a Tensor

In [53]:
# Let's say we have a 2D array
dd = [
[1,2,3],
[4,5,6],
[7,8,9]
]

In [54]:
#To work with this tensor's shape, we’ll create a tensor object like so:
t = tf.constant(dd) # constant() is a function that helps you create a constant tensor
t

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [34]:
type(t) # To get the type of object t

tensorflow.python.framework.ops.EagerTensor

In [35]:
# Now, we have a Tensor object, and so we can ask to see the tensor's shape:
t.shape

TensorShape([3, 3])

In [57]:
df=[
[1,2,3,10],
[4,5,6,11],
[7,8,9,12],
[13,14,19,20]
]

In [58]:
tt = tf.constant(df) # constant() is a function that helps you create a constant tensor
tt

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12],
       [13, 14, 19, 20]], dtype=int32)>

In [59]:
type(tt)

tensorflow.python.framework.ops.EagerTensor

In [60]:
tt.shape

TensorShape([4, 4])

### Reshaping A Tensor In TensorFlow

In [36]:
t = tf.constant([
 [1,1,1,1],
 [2,2,2,2],
 [3,3,3,3]
], dtype=tf.float32) # can also mention the type of the element we want in the tensor

In [37]:
reshaped_tensor = tf.reshape(t, [1,12]) # reshape is a function that helps to reshaping any ndarray or ndtensor
print(reshaped_tensor)

tf.Tensor([[1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3.]], shape=(1, 12), dtype=float32)


In [38]:
reshaped_tensor = tf.reshape(t, [2,6]) # change the reshape row and column 
print(reshaped_tensor)

tf.Tensor(
[[1. 1. 1. 1. 2. 2.]
 [2. 2. 3. 3. 3. 3.]], shape=(2, 6), dtype=float32)


In [39]:
reshaped_tensor = tf.reshape(t, [3,4])
print(reshaped_tensor)

tf.Tensor(
[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]], shape=(3, 4), dtype=float32)


In [40]:
reshaped_tensor = tf.reshape(t, [2,2,3])
print(reshaped_tensor)

tf.Tensor(
[[[1. 1. 1.]
  [1. 2. 2.]]

 [[2. 2. 3.]
  [3. 3. 3.]]], shape=(2, 2, 3), dtype=float32)


In [68]:
t1 = tf.constant([
 [11,12,13,14],
 [22,25,26,27]
], dtype=tf.float32)

In [69]:
reshaped_tensor1 = tf.reshape(t1, [1,8]) # reshape is a function that helps to reshaping any ndarray or ndtensor
print(reshaped_tensor1)

tf.Tensor([[11. 12. 13. 14. 22. 25. 26. 27.]], shape=(1, 8), dtype=float32)


In [73]:
reshaped_tensor1 = tf.reshape(t1, [2,4]) # change the reshape row and column 
print(reshaped_tensor1)

tf.Tensor(
[[11. 12. 13. 14.]
 [22. 25. 26. 27.]], shape=(2, 4), dtype=float32)


In [75]:
reshaped_tensor1 = tf.reshape(t1, [2,2,2])
print(reshaped_tensor1)

tf.Tensor(
[[[11. 12.]
  [13. 14.]]

 [[22. 25.]
  [26. 27.]]], shape=(2, 2, 2), dtype=float32)


### Changing Shape By Squeezing And Unsqueezing

In [41]:
print(tf.reshape(t, [1,12]))

tf.Tensor([[1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3.]], shape=(1, 12), dtype=float32)


In [42]:
print(tf.reshape(t, [1,12]).shape)

(1, 12)


In [43]:
print(tf.squeeze(tf.reshape(t, [1,12])))

tf.Tensor([1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3.], shape=(12,), dtype=float32)


In [44]:
print(tf.squeeze(tf.reshape(t, [1,12])).shape)

(12,)


In [76]:
print(tf.squeeze(tf.reshape(t1, [1,8])))

tf.Tensor([11. 12. 13. 14. 22. 25. 26. 27.], shape=(8,), dtype=float32)


In [77]:
print(tf.squeeze(tf.reshape(t1, [1,8])).shape)

(8,)


### Flatten A Tensor

In [45]:
def flatten(t):
    t = tf.reshape(t, [1, -1])
    t = tf.squeeze(t)
    return t

In [46]:
t = tf.ones([4, 3])
t

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [47]:
flatten(t)

<tf.Tensor: shape=(12,), dtype=float32, numpy=array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)>

### Concatenating Tensors

In [48]:
t1 = tf.constant([
 [1,2],
 [3,4]
])
t2 = tf.constant([
 [5,6],
 [7,8]
])

In [49]:
tf.concat((t1, t2), axis = 0) # concat() helps you to concatenate two tensors according to the given axis

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]], dtype=int32)>

In [50]:
tf.concat((t1, t2), axis = 1)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 5, 6],
       [3, 4, 7, 8]], dtype=int32)>

In [51]:
tf.concat((t1, t2), axis = 0).shape

TensorShape([4, 2])

In [52]:
tf.concat((t1, t2), axis = 1).shape

TensorShape([2, 4])

In [78]:
t4 = tf.constant([
 [1,2,9],
 [3,4,10]
])
t5 = tf.constant([
 [5,6,11],
 [7,8,12]
])

In [79]:
tf.concat((t4, t5), axis = 0)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  9],
       [ 3,  4, 10],
       [ 5,  6, 11],
       [ 7,  8, 12]], dtype=int32)>

In [80]:
tf.concat((t4, t5), axis = 1)

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 1,  2,  9,  5,  6, 11],
       [ 3,  4, 10,  7,  8, 12]], dtype=int32)>

In [81]:
tf.concat((t4, t5), axis = 0).shape

TensorShape([4, 3])

In [82]:
tf.concat((t4, t5), axis = 1).shape

TensorShape([2, 6])